#!/bin/bash

# Script for archiving multiple users
USER=$1

printf "Executing script: ${0}\n"
for USER in ${$@}
do
    printf "Archiving user: ${USER}\n"
    # Lock the account
    passwd -l ${USER}
    # Create an archive of the home directory
    tar cf /archives/${USER}.tar.gz /home/${USER}
done
