#!/bin/bash

# Script archives a user

printf "Executing script: $0\n"
printf "Archiving user: $1\n"

# Lock the account
passwd -l $1

# Create an archive of the home directory
tar cf /archives/${1}.tar.gz /home/${1}
