#!/bin/bash
#
#: Title        : archive-multiple-users
#: Date         : 2020-08-11
#: Author       : "Alvaro Lupercio" <lupera1@jhuapl.edu>
#: Version      : 1.0
#: Description  : script archives multiple users and locks their accounts
# Script for archiving multiple users

USER=$1

printf "Executing script: ${0}\n"
for USER in "$@"
do
    printf "Archiving user: ${USER}\n"
    # Lock the account
    passwd -l ${USER}
    # Create an archive of the home directory
    tar cf /archives/${USER}.tar.gz /home/${USER}
done
