#!/bin/bash
#
#: Title        : archive-user
#: Date         : 2020-08-11
#: Author       : "Alvaro Lupercio" <lupera1@jhuapl.edu>
#: Version      : 1.0
#: Description  : script archives the user provided and locks the user account

# Script archives a user

printf "Executing script: $0\n"
printf "Archiving user: $1\n"

# Lock the account
passwd -l $1

# Create an archive of the home directory
tar cf /archives/${1}.tar.gz /home/${1}
