#!/bin/bash
#
#: Title        : archive-user
#: Date         : 2020-08-11
#: Author       : "Alvaro Lupercio" <lupera1@jhuapl.edu>
#: Version      : 1.0
#: Description  : script archives the user provided and locks the user account

# Script prompts user for name to archive
read -p "Enter a user name: " USER
printf "Archiving user: ${USER}\n"

# Lock the account
passwd -l $USER

# Create an archive of the home directory
tar cf /archives/${USER}.tar.gz /home/${USER}

# Removing the user account from system
printf "Removing ${USER} from system\n"
userdel -r ${USER}
