#!/bin/bash
#
#: Title        : rename-file
#: Date         : 2020-08-12
#: Author       : "Alvaro Lupercio" <lupera1@jhuapl.edu>
#: Version      : 1.0
#: Description  : script renames files

# Script renames all files that end in jpg by inserting the date

PICTURES=$(ls *jpg)
DATE=$(date +%F)

for PICTURE in ${PICTURES}
do
    printf "Renaming ${PICTURE} to ${DATE}-${PICTURE}\n"
    mv ${PICTURE} ${DATE}-${PICTURE}
done
