#!/bin/bash

# Script renames all files that end in jpg by inserting the date

PICTURES=$(ls *jpg)
DATE=$(date +%F)

for PICTURE in ${PICTURES}
do
    printf "Renaming ${PICTURE} to ${DATE}-${PICTURE}\n"
    mv ${PICTURE} ${DATE}-${PICTURE}
done
