#!/bin/bash
#
#: Title	: set-ipstatic
#: Date 	: 2020-11-06
#: Author	: "Alvaro Lupercio" <lupera1@jhuapl.edu>
#: Version	: 1.0
#: Description	: sets network interface address from dhcp to static

# ensure script is being executed with superuser privileges.
if [[ "${UID}" -ne 0 ]]
then
    echo 'Please run with sudo privileges or as root.'
    exit 1
fi

# get network interface name and protocol
NIC=$(nmcli connection show | sed -n 2p | cut -d' ' -f1)
PROTO=$(nmcli connection show id ${NIC} | grep -i ipv4.method)

if [[ ${PROTO} != "auto" ]]
then
    # get current ip address and subnet mask
    IPADDR=$(ip a | grep inet | grep -v inet6 | sed -n 2p | cut -d' ' -f6)

    # get default gateway
    GW=$(ip route | sed -n 1p | cut -d' ' -f3)

    # change nic settings to static
    nmcli connection modify ${NIC} ipv4.address ${IPADDR}
    nmcli connection modify ${NIC} ipv4.gateway ${GW}
    nmcli connection modify ${NIC} ipv4.method manual
    nmcli connection modify ${NIC} ipv4.dns "192.168.1.192"
    nmcli connection modify ${NIC} ipv4.dns-search "demo.net"

    # restart network manager service
    systemctl restart NetworkManager

    exit 0
else
    printf "Already static\n"
    exit 0
fi
