#!/bin/bash
#
#: Title        : sync-new-repos
#: Date         : 2021-04-06
#: Author       :"AB1-Linux" <lupera1@jhuapl.edu>
#: Version      : 1.0
#: Description  : Script syncs downloaded rpms and runs createrepo on all repodata

# ensure script is being executed with superuser privileges.
if [[ "${UID}" -ne 0 ]]
then
    echo 'Please run with sudo privileges or as root.'
    exit 1
fi

REPO='/data/repos'
RHEL6_SVR_REPO='/fs/repodata/rhel/rhel6-svr'
RHEL6_WS_REPO='/fs/repodata/rhel/rhel6-ws'
RHEL7_SVR_REPO='/fs/repodata/rhel/rhel7-svr'
RHEL7_WS_REPO='/fs/repodata/rhel/rhel7-ws'

RHEL6_SVR_RPMS=$(ls $REPO | grep -Ei 'rhel-6-server|rhscl-6' | grep -v workstation)
RHEL7_SVR_RPMS=$(ls $REPO | grep -Ei 'rhel-7-server|rhscl-7' | grep -v workstation)
RHEL6_WS_RPMS=$(ls $REPO | egrep -Ei 'rhel-6|workstation' | grep -Ev 'server|rhscl-7|rhel-7')
RHEL7_WS_RPMS=$(ls $REPO | egrep -Ei 'rhel-7|workstation' | grep -Ev 'server|rhscl-6|rhel-6')
RHEL8_RPMS=$(find $REPO -maxdepth 1 -name '*rhel-8*')
EPEL_RPMS=$(ls -d $REPO/*EPEL*)

function rhel8sync {
    for dir in $RHEL8_RPMS
    do
        printf "\nSyncing $dir ...\n"
        rsync -ac $dir /fs/repodata/rhel/rhel8/ | pv
    done
}

function epelsync {
    for dir in $EPEL_RPMS
    do
        if [[ "$dir" == *"6"* ]]
        then
            printf "\nSyncing $dir ...\n"
            rsync -ac $dir/* /fs/repodata/rhel/epel/rhel6/ | pv
            sleep 2s
            printf "\nCreating repo /fs/repodata/rhel/epel/rhel6 ...\n"
            createrepo /fs/repodata/rhel/epel/rhel6 | pv
        elif [[ "$dir" == *"7"* ]]
        then
            printf "\nSyncing $dir ...\n"
            rsync -ac $dir/* /fs/repodata/rhel/epel/rhel7/ | pv
            sleep 2s
            printf "\nCreating repo /fs/repodata/rhel/epel/rhel7 ...\n"
            createrepo /fs/repodata/rhel/epel/rhel7
        else
            printf "\nSyncing $dir ...\n"
            rsync -ac $dir/* /fs/repodata/rhel/epel/rhel8/ | pv
            sleep 2s
            printf "\nCreating /fs/repodata/rhel/epel/rhel8 ...\n"
            createrepo /fs/repodata/rhel/epel/rhel8 | pv
        fi
    done
}

function rhel6sync-svr {
    for dir in $RHEL6_SVR_RPMS
    do
        printf "\nSyncing $dir ...\n"
        rsync -ac $REPO/$dir/* $RHEL6_SVR_REPO/$dir | pv
        sleep 2s
        printf "\nCreating repo $RHEL6_SVR_REPO/$dir\n"
        createrepo $RHEL6_SVR_REPO/$dir | pv
    done
}

function rhel6sync-ws {
    for dir in $RHEL6_WS_RPMS
    do
        printf "\nSyncing $dir ...\n"
        rsync -ac $REPO/$dir/* $RHEL6_WS_REPO/$dir | pv
        sleep 2s
        printf "\nCreating repo $RHEL6_WS_REPO/$dir ...\n"
        createrepo $RHEL6_WS_REPO/$dir | pv
    done
}

function rhel7sync-svr {
    for dir in $RHEL7_SVR_RPMS
    do
        printf "\nSyncing $dir ...\n"
        rsync -ac $REPO/$dir/* $RHEL7_SVR_REPO/$dir | pv
        sleep 2s
        printf "\nCreating repo $RHEL7_SVR_REPO/$dir ...\n"
        createrepo $RHEL6_WS_REPO/$dir | pv
    done
}

function rhel7sync-ws {
    for dir in $RHEL7_WS_RPMS
    do
        printf "\nSyncing $dir ...\n"
        rsync -ac $REPO/$dir/* $RHEL7_WS_REPO/$dir | pv
        sleep 2s
        printf "\nCreating repo $RHEL7_WS_REPO/$dir ...\n"
        createrepo $RHEL7_WS_REPO/$dir | pv
    done
}

rhel6sync-svr
rhel7sync-svr
rhel6sync-ws
rhel7sync-ws
epelsync
rhel8sync
