#!/bin/bash
#
#: Title        : tarfile-download
#: Date         : 2021-04-06
#: Author       :"AB1-Linux" <lupera1@jhuapl.edu>
#: Version      : 1.0
#: Description  : Script downloads RHEL(6-7) repo tarfiles from apllinuxdepot

# ensure script is being executed with superuser privileges.
if [[ "${UID}" -ne 0 ]]
then
    echo 'Please run with sudo privileges or as root.'
    exit 1
fi

REPO='/data/repos'
RHEL6_SVR_REPO='/fs/repodata/rhel/rhel6-svr'

RHEL6_SVR_RPMS=$(ls $REPO | grep -Ei 'rhel-6-server|rhscl-6' | grep -v workstation)

for dir in $RHEL6_SVR_RPMS
do
    printf "Syncing rhel6-svr rpms ..."
    rsync -ac $REPO/$dir $RHEL6_SVR_REPO/$dir | pv
done
